# Generated by Django 2.1.5 on 2019-01-12 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('a', 'Vorspeise'), ('m', 'Hauptgang'), ('d', 'Nachspeise')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('description_de', models.TextField(max_length=1000)),
                ('description_en', models.TextField(max_length=1000)),
                ('date', models.DateField()),
                ('end_registration', models.DateField()),
                ('appetizer_time', models.DateTimeField()),
                ('main_course_time', models.DateTimeField()),
                ('dessert_time', models.DateTimeField()),
                ('afterparty_time', models.DateTimeField()),
                ('afterparty_location', models.CharField(max_length=70)),
                ('active', models.BooleanField(default=False)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rudi.Advisor')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('doorbell', models.CharField(blank=True, max_length=200, null=True)),
                ('participant_1_firstname', models.CharField(max_length=50)),
                ('participant_1_lastname', models.CharField(max_length=50)),
                ('participant_1_email', models.EmailField(max_length=254)),
                ('participant_1_phone', models.CharField(max_length=50)),
                ('participant_2_firstname', models.CharField(max_length=50)),
                ('participant_2_lastname', models.CharField(max_length=50)),
                ('participant_2_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('participant_2_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('allergies', models.TextField(blank=True, max_length=500, null=True)),
                ('code', models.CharField(editable=False, max_length=64, unique=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('has_confirmed_email', models.BooleanField(default=False)),
                ('sent_assignment_mail', models.BooleanField(default=False)),
                ('dislike', models.ManyToManyField(blank=True, related_name='dislike', to='rudi.Course')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rudi.Event')),
                ('like', models.ManyToManyField(blank=True, related_name='like', to='rudi.Course')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef', to='rudi.Team'),
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rudi.Course'),
        ),
        migrations.AddField(
            model_name='group',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rudi.Event'),
        ),
        migrations.AddField(
            model_name='group',
            name='member1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='rudi.Team'),
        ),
        migrations.AddField(
            model_name='group',
            name='member2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='rudi.Team'),
        ),
    ]
